stages:
    - prepare
    - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  
composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install
        
generate:
    stage: build
    image: php:7.1-cli
    script:
        - vendor/bin/statie generate source
   