stages:
    - prepare
    - build
    - docker
    
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - output/
  - node_modules/
  
composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install

node:
    stage: prepare
    image: node:latest
    script:
      - npm install

statie:
    stage: build
    image: php:7.1-cli
    script:
        - vendor/bin/statie generate source

assets:
  stage: build
  image: node:latest
  script:
    - npx webpack

build:
    stage: docker
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz .
        - docker push $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz
