stages:
    - prepare
    - build
    - docker
    
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - html/
  - node_modules/
  
composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install
    only:
      - tags
      - master

node:
    stage: prepare
    image: node:latest
    script:
      - npm install
    only:
      - tags
      - master

statie-beta:
    stage: build
    image: php:7.1-cli
    script:
      - vendor/bin/statie generate source -c statie_beta.yml --output=html
    only:
      - master

statie:
    stage: build
    image: php:7.1-cli
    script:
      - vendor/bin/statie generate source -c statie.yml --output=html
    only:
      - tags

assets:
    stage: build
    image: node:latest
    script:
      - npx webpack
    only:
      - tags
      - master

build-beta:
    stage: docker
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u jakubenglicky -p b216e0d6-7aa2-49e2-9510-8e793d389ad6
      - docker build -t jakubenglicky/skoleninasbavi-cz:beta .
      - docker push jakubenglicky/skoleninasbavi-cz:beta
    only:
      - master

build:
    stage: docker
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u jakubenglicky -p b216e0d6-7aa2-49e2-9510-8e793d389ad6
      - docker build -t jakubenglicky/skoleninasbavi-cz .
      - docker push jakubenglicky/skoleninasbavi-cz
    only:
      - tags
