stages:
    - deploy

prepare-docker:
    stage: deploy
    image: docker:stable
    before_script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.example.com
    script:
        - ls