stages:
    - build

composer:
    stage: build
    image: composer:latest
    script:
        - composer install
        
generate:
    stage: build
    image: php:7.1-cli
    dependencies:
        - build:composer
    script:
        - vendor/bin/statie generate source
   