stages:
    - prepare
    - build
    - docker
    
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - output/
  - node_modules/
  
composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install
    only:
      - tags
      - master

node:
    stage: prepare
    image: node:latest
    script:
      - npm install
    only:
      - tags
      - master

statie-beta:
    stage: build
    image: php:7.1-cli
    script:
      - vendor/bin/statie generate source -c statie_beta.yml
    only:
      - master

statie:
    stage: build
    image: php:7.1-cli
    script:
      - vendor/bin/statie generate source -c statie.yml
    only:
      - tags

assets:
    stage: build
    image: node:latest
    script:
      - npx webpack
    only:
      - tags
      - master

build-beta:
    stage: docker
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz:beta .
      - docker push $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz:beta
    only:
      - master

build:
    stage: docker
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz .
      - docker push $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz
    only:
      - tags
