stages:
    - prepare
    - build
    - deploy
    
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - output/
  
composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install
        
generate:
    stage: build
    image: php:7.1-cli
    script:
        - vendor/bin/statie generate source
        
build-docker:
    stage: deploy
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz .
        - docker push $CI_REGISTRY/jakubenglicky/skoleninasbavi-cz
