stages:
    - prepare
    - build

composer:
    stage: prepare
    image: composer:latest
    script:
        - composer install
        
generate:
    stage: build
    image: php:7.1-cli
    dependencies:
        - prepare
    script:
        - vendor/bin/statie generate source
   