stages:
    - deploy

prepare-docker:
    stage: deploy
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
