version: '3'

services:
  web:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    environment:
      VIRTUAL_HOST: skoleninasbavi.cz.test

  statie:
    image: php:7.3-cli
    volumes:
      - ./:/app
    entrypoint: vendor/bin/statie generate source --output=html --config=statie_local.yml
    working_dir: /app
    depends_on:
      - composer
      - assets

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    command: install

  assets:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: npm install -D

  payments:
    image: node:latest
    volumes:
      - ./payments:/app
    working_dir: /app
    command: node server.js
    environment:
      VIRTUAL_HOST: payments.skoleninasbavi.cz.test
      VIRTUAL_PORT: 4242
    ports:
    - 4242:4242

networks:
  default:
    external:
      name: nginx-proxy

