version: '3'

services:
  web:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - 80
    environment:
      VIRTUAL_HOST: skoleninasbavi.cz.test

  statie:
    image: php:7.3-cli
    volumes:
      - ./:/app
    entrypoint: vendor/bin/statie
    working_dir: /app

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    command: install

  assets:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: npm install -D

networks:
  default:
    external:
      name: nginx-proxy

