version: '3'

services:
  web:
    image: peckadesign/php:7.4-dev
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80

  statie:
    image: php:7.3-cli
    volumes:
      - ./:/app
    entrypoint: vendor/bin/statie generate source --output=html --config=statie_local.yml
    working_dir: /app
    depends_on:
      - composer
      - assets

  composer:
    image: peckadesign/php:7.4-dev
    volumes:
      - ./:/app
    command: composer install

  assets:
    image: node:14
    volumes:
      - ./:/app
    working_dir: /app
    command: npm install -D

  payments:
    image: node:latest
    volumes:
      - ./payments:/app
    working_dir: /app
    command: node server.js
    environment:
      VIRTUAL_HOST: payments.skoleninasbavi.cz.test
      VIRTUAL_PORT: 4242
    ports:
    - 4242:4242


