name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npx webpack

      - name: Static generator
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          coverage: none # default is xdebug
        - run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
        - run: make static

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html